# nixpacks.toml

[phases.setup]
# Stelle sicher, dass sowohl die Node.js-Umgebung als auch die Schriftarten installiert werden.
# "nodejs_20" ist ein Beispiel für Node.js Version 20. Passe die Version ggf. an
# die Version an, die du verwenden möchtest (z.B. "nodejs_18").
# Überprüfe verfügbare Nix-Paketnamen für Node.js auf https://search.nixos.org/packages
nixPkgs = ["nodejs_20", "dejavu_fonts"]

# WICHTIG: Wenn du eine andere Node.js Version brauchst, ersetze "nodejs_20"
# durch das entsprechende Nix-Paket (z.B. nodejs_18, nodejs_16 etc.)
